/*************************************************************************
 * Extract Speech-to-Text Transcripts from Premiere Pro
 *
 * This ExtendScript extracts transcripts generated by Premiere's
 * Speech-to-Text feature from clips in the active sequence or project.
 *
 * Unlike caption tracks, Speech-to-Text data is stored as metadata
 * attached to the source clip's projectItem.
 *
 * Returns JSON string with array of transcript objects:
 * [{
 *    "clipName": "<name>",
 *    "filePath": "<path>",
 *    "segments": [{ "start": <seconds>, "end": <seconds>, "text": "<text>" }]
 * }]
 **************************************************************************/

(function() {
  try {
    // Step 1: Get the active project
    var project = app.project;
    if (!project) {
      return JSON.stringify({
        success: false,
        error: "No active project found"
      });
    }

    // Step 2: Collect all unique project items that might have transcripts
    var projectItemsToCheck = {};
    var transcriptsArray = [];

    // Helper function to add a project item to check list
    function addProjectItem(projectItem) {
      if (!projectItem || !projectItem.nodeId) return;

      var nodeId = projectItem.nodeId;
      if (!projectItemsToCheck[nodeId]) {
        projectItemsToCheck[nodeId] = projectItem;
      }
    }

    // Method 1: Check active sequence clips
    var seq = project.activeSequence;
    if (seq) {
      // Check all audio tracks for clips
      if (seq.audioTracks) {
        for (var t = 0; t < seq.audioTracks.numTracks; t++) {
          try {
            var track = seq.audioTracks[t];
            if (track && track.clips) {
              for (var c = 0; c < track.clips.numItems; c++) {
                try {
                  var clip = track.clips[c];
                  if (clip && clip.projectItem) {
                    addProjectItem(clip.projectItem);
                  }
                } catch (e) {
                  // Skip this clip
                }
              }
            }
          } catch (e) {
            // Skip this track
          }
        }
      }

      // Check all video tracks for clips
      if (seq.videoTracks) {
        for (var t = 0; t < seq.videoTracks.numTracks; t++) {
          try {
            var track = seq.videoTracks[t];
            if (track && track.clips) {
              for (var c = 0; c < track.clips.numItems; c++) {
                try {
                  var clip = track.clips[c];
                  if (clip && clip.projectItem) {
                    addProjectItem(clip.projectItem);
                  }
                } catch (e) {
                  // Skip this clip
                }
              }
            }
          } catch (e) {
            // Skip this track
          }
        }
      }
    }

    // Method 2: Also check all project items recursively
    function checkProjectItemRecursive(item) {
      if (!item) return;

      // Add this item
      addProjectItem(item);

      // Check children
      if (item.children && item.children.numItems > 0) {
        for (var i = 0; i < item.children.numItems; i++) {
          try {
            checkProjectItemRecursive(item.children[i]);
          } catch (e) {
            // Skip this child
          }
        }
      }
    }

    // Check root bin
    if (project.rootItem) {
      checkProjectItemRecursive(project.rootItem);
    }

    // Step 3: Extract transcripts from each project item
    for (var nodeId in projectItemsToCheck) {
      try {
        var projectItem = projectItemsToCheck[nodeId];

        // Get item name and file path
        var itemName = projectItem.name || "Unnamed";
        var filePath = "";

        try {
          if (projectItem.getMediaPath) {
            filePath = projectItem.getMediaPath();
          }
        } catch (e) {
          // getMediaPath not available
        }

        // Try multiple methods to access transcript data
        var transcriptData = null;

        // Method A: Check if projectItem has transcript metadata
        // In newer Premiere versions, transcripts might be exposed via XMP metadata
        try {
          if (projectItem.getXMPMetadata) {
            var xmpString = projectItem.getXMPMetadata();

            // Parse XMP for transcript data
            // Look for patterns like:
            // - <xmpDM:transcript>
            // - <premiere:speechToText>
            // - <dc:description> (sometimes used for transcripts)

            if (xmpString.indexOf("transcript") !== -1 ||
                xmpString.indexOf("speechToText") !== -1 ||
                xmpString.indexOf("speech-to-text") !== -1) {

              // Found potential transcript data
              // Try to extract structured data
              transcriptData = {
                clipName: itemName,
                filePath: filePath,
                xmpData: xmpString,
                source: "xmp"
              };
            }
          }
        } catch (e) {
          // XMP metadata not available or error accessing it
        }

        // Method B: Check if there's a transcript property directly
        try {
          if (projectItem.transcript) {
            transcriptData = {
              clipName: itemName,
              filePath: filePath,
              transcript: projectItem.transcript,
              source: "direct_property"
            };
          }
        } catch (e) {
          // Direct property not available
        }

        // Method C: Check markers for transcript data
        // Sometimes transcripts are stored as markers
        try {
          if (projectItem.getMarkers) {
            var markers = projectItem.getMarkers();
            if (markers && markers.numMarkers > 0) {
              var transcriptMarkers = [];

              for (var m = 0; m < markers.numMarkers; m++) {
                try {
                  var marker = markers[m];
                  if (marker && marker.comments) {
                    var comments = marker.comments.toLowerCase();
                    if (comments.indexOf("transcript") !== -1 ||
                        comments.indexOf("speech") !== -1) {
                      transcriptMarkers.push({
                        time: marker.start ? marker.start.seconds : 0,
                        text: marker.comments
                      });
                    }
                  }
                } catch (e) {
                  // Skip this marker
                }
              }

              if (transcriptMarkers.length > 0) {
                transcriptData = {
                  clipName: itemName,
                  filePath: filePath,
                  markers: transcriptMarkers,
                  source: "markers"
                };
              }
            }
          }
        } catch (e) {
          // Markers not available
        }

        // Method D: Check for attached transcript files
        // Sometimes Premiere stores transcripts as sidecar files
        try {
          if (projectItem.attachments) {
            // Check for .srt, .vtt, .txt files
            for (var a = 0; a < projectItem.attachments.length; a++) {
              var attachment = projectItem.attachments[a];
              if (attachment && attachment.path) {
                var attPath = attachment.path.toLowerCase();
                if (attPath.indexOf(".srt") !== -1 ||
                    attPath.indexOf(".vtt") !== -1 ||
                    attPath.indexOf("transcript") !== -1) {
                  transcriptData = {
                    clipName: itemName,
                    filePath: filePath,
                    attachmentPath: attachment.path,
                    source: "attachment"
                  };
                  break;
                }
              }
            }
          }
        } catch (e) {
          // Attachments not available
        }

        // Method E: Check project item metadata
        // Sometimes transcription status is in metadata
        try {
          // Check if item has transcription status
          var hasTranscript = false;

          // Try to access internal properties (may not work in all versions)
          if (projectItem.transcriptionStatus) {
            hasTranscript = projectItem.transcriptionStatus === "completed" ||
                           projectItem.transcriptionStatus === "Completed";
          }

          if (hasTranscript && !transcriptData) {
            transcriptData = {
              clipName: itemName,
              filePath: filePath,
              status: "completed",
              note: "Transcript marked as completed but data not directly accessible",
              source: "status_only"
            };
          }
        } catch (e) {
          // Metadata access failed
        }

        // If we found transcript data, add it to array
        if (transcriptData) {
          transcriptsArray.push(transcriptData);
        }

      } catch (e) {
        // Skip this project item
        continue;
      }
    }

    // Step 4: Return results
    if (transcriptsArray.length === 0) {
      return JSON.stringify({
        success: false,
        error: "No transcripts found. Transcripts may be stored in Adobe cache directories rather than directly accessible via ExtendScript API.",
        suggestion: "Check ~/Library/Application Support/Adobe/Common/MetadataIndexer/Transcripts-1/",
        itemsChecked: Object.keys(projectItemsToCheck).length
      });
    }

    // Return success with all transcripts
    return JSON.stringify({
      success: true,
      projectName: project.name || "Unnamed",
      totalTranscripts: transcriptsArray.length,
      itemsChecked: Object.keys(projectItemsToCheck).length,
      transcripts: transcriptsArray
    });

  } catch (e) {
    // Return error if something went wrong
    return JSON.stringify({
      success: false,
      error: e.toString() + " (Line: " + (e.line || "unknown") + ")",
      transcripts: []
    });
  }
})();
